apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hlybot
  name: hlybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hlybot
  template:
    metadata:
      labels:
        app: hlybot
    spec:
      containers:
        - image: docker.io/bevisy/hlybot:latest
          imagePullPolicy: IfNotPresent
          name: hlybot-server
          args:
          - server
          env:
            - name: HLYBOT_BOTTOKEN
              value: {}
            - name: HLYBOT_DEBUG
              value: {}
            - name: HLYBOT_DSTURL
              value: {}
            - name: HLYBOT_USERID
              value: {}
            - name: HLYBOT_PUSHINTERVAL
              value: {}
            - name: HTTPS_PROXY
              value: {}
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - name: ca
              mountPath: /etc/ssl/certs/ca-certificates.crt
          securityContext:
            allowPrivilegeEscalation: false
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: ca
          hostPath:
            path: /etc/ssl/certs/ca-certificates.crt
            type: "File"
